### ISSUE TITLE
Requests for some effects!

### ISSUE THREAD

**Issue by chrisalleng** [punkUser/xwing_math#1]
I might be stupid, but I don't see a way to do any of:

C3PO
Palpatine
Crack Shots

**Comment by punkUser** [comment]
Not stupid, those are indeed not there yet :)

I've added C-3P0 now to both of the forms - you can guess 0 or 1 from the basic form, or guess whatever value you want from the Advanced form. Let me know if you run into any trouble with it.

I'll add Crack Shot next and document the defender token spending logic around it. I imagine the most useful will be to have the defender spend extra tokens to mitigate against potential crack shots. This will make it tend to do better in regular single attack situations but potentially slightly worse in Gunner type cases, but since the logic already doesn't go out of its way to try and reason about expected damage from gunner attacks (as explained in the FAQ), this is likely the most consistent. Let me know if you'd like different logic though here.

For Palpatine, do you just want an option to palp a crit or evade depending on attack/defense unconditionally?

**Comment by chrisalleng** [comment]
Awesome, thanks so much!  Not looking for anything complicated, the ability to guess numbers other than zero is already way more than I would have even hoped for.

I think that's the best call on Palpatine, yeah.  Thanks again!

**Comment by punkUser** [comment]
Ok I've added Palpatine and Crack Shot now as well and pushed it to the live site. Please let me know if they work the way that you are expecting. Some of the interactions with other effects are a bit non-trivial especially in cases where they aren't possible in the game currently: ex. if you palp an evade with C-3P0 and sunny bounder, what order is that all supposed to resolve in? :) So for now it's somewhat arbitrary best guess.

Anyways if it all seems to work the way that you expect, feel free to close the issue. As always feel free to open additional issues if you notice bugs or have additional features you'd like to see.

**Comment by chrisalleng** [comment]
Sorry, forgot to close the issue! Thanks again! And, I think arbitrary guesses for those effects is fine - it's not like those combinations are possible currently at least :)
